-- 코드를 입력하세요
SELECT DISTINCT(cc.CAR_ID)
FROM CAR_RENTAL_COMPANY_CAR cc
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY rh
    on cc.CAR_ID=rh.CAR_ID
WHERE cc.CAR_TYPE = '세단' and MONTH(rh.START_DATE) = 10
ORDER BY 1 DESC;